### ISSUE TITLE
macOS Sonoma app quits immediately

### ISSUE THREAD

**Issue by tmstiller** [j4321/tkColorPicker#12]
Mac OSX (14.6.1 (23G93)) app was built with pyinstaller (6.10.0) using tkcolorpicker quits immediately but launches successfully when built using tkinter.colorchooser.
Analysis of launch failure yields:
Traceback (most recent call last):
  File "color_swatch.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "tkcolorpicker/__init__.py", line 21, in <module>

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "tkcolorpicker/colorpicker.py", line 43, in <module>
TypeError: 'NoneType' object is not subscriptable

**Comment by tmstiller** [comment]
Made local copy of the tkcolorpicker code and  changed the  tkcolorpicker module, line 42,  exception from "ValueError" to "TypeError" and recompiled.

Issue resolved
